# Generated by Django 4.0.5 on 2022-06-24 12:47

import admin_panel.database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.company')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=admin_panel.database.models.car_photo_location_and_rename)),
                ('one_to_three', models.DecimalField(decimal_places=0, max_digits=5)),
                ('four_to_six', models.DecimalField(decimal_places=0, max_digits=5)),
                ('seven_to_thirteen', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fourteen_to_twenty', models.DecimalField(decimal_places=0, max_digits=5)),
                ('twenty_one_plus', models.DecimalField(decimal_places=0, max_digits=5)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.carbrand')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='database.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.cartype')),
            ],
        ),
    ]
