# Generated by Django 4.0.5 on 2022-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_car_daily_limit_car_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
