# Generated by Django 4.0.5 on 2022-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='colors',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
