# Generated by Django 4.0.5 on 2022-06-27 12:18

import admin_panel.database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_car_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gallery',
            field=models.ImageField(default=1, upload_to=admin_panel.database.models.car_photo_location_and_rename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
