# Generated by Django 4.0.5 on 2022-06-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_multiimages_remove_car_gallery_car_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='gallery',
        ),
        migrations.AddField(
            model_name='multiimages',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.car'),
        ),
    ]
