# Generated by Django 4.0.5 on 2022-07-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_car_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
