# Generated by Django 4.0.5 on 2022-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_delete_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='channel_id',
            field=models.BigIntegerField(default=-1001767381464, unique=True),
            preserve_default=False,
        ),
    ]
