# Generated by Django 4.0.5 on 2022-07-04 11:40

import admin_panel.database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_company_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('feet', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='MultiImages',
            new_name='MultiImagesCar',
        ),
        migrations.CreateModel(
            name='MultiImagesYacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=admin_panel.database.models.car_photo_location_and_rename)),
                ('yacht', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.yacht')),
            ],
        ),
    ]
