# Generated by Django 4.0.5 on 2022-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_yacht_rename_multiimages_multiimagescar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
