# Generated by Django 4.0.5 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_yacht_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
